[package]
name = "flag-algebra"
version = "0.1.11"
authors = ["Rémi de Verclos <remi.de.verclos@gmail.com>"]
description = "An implementation of Razborov's flag algebras"
publish = true
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/flag-algebra"
repository = "https://github.com/avangogo/rust-flag-algebra"
license = "GPL-3.0"
keywords = ["flag", "algebra", "graph", "combinatorics"]

[dependencies]
num = "0.3.0"
sprs = { version = "0.9.1", features = ["serde"] }
ndarray = "0.13.1"
find_folder = "0.3.0"
rand = "0.7.3"
serde = "1.0.116"
serde_derive = "1.0.116"
bincode = "1.3.1"
canonical-form = "0.9.4"
typenum = "1.12.0"
svg = "0.8.0"
simplelog = "0.8.0"
ndarray-linalg = { version = "0.12.1", features = ["netlib"] }
failure = "0.1.8"
failure_derive = "0.1.8"
arrayvec = "0.5.1"
log = "0.4.11"

[dev-dependencies]
criterion = "0.3.3"

#[[bench]]
#name = "my_benchmark"
#harness = false
#debug = true
