[package]
name = "flag-algebra"
version = "0.1.6"
authors = ["Rémi de Verclos <r.deverclos@math.ru.nl>"]
description = "An implementation of Razborov's flag algebras"
publish = true
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/flag-algebra"
repository = "https://github.com/avangogo/rust-flag-algebra"
license = "GPL-3.0"
keywords = ["flag", "algebra", "graph", "combinatorics"]

[dependencies]
num = "0.2.1"
sprs = { version = "0.7.1", features = ["serde", "serde_derive"] }
ndarray = "0.13.0"
find_folder = "0.3.0"
rand = "0.7.3"
serde = "1.0.104"
serde_derive = "1.0.104"
bincode = "1.2.1"
canonical-form = "0.9.2"
typenum = "1.11.2"
svg = "0.6.0"
log = "0.4.8"
simplelog = "0.7.4"
ndarray-linalg = { version = "0.12.0", features = ["netlib"] }
failure = "0.1.6"
failure_derive = "0.1.6"
arrayvec = "0.5.1"
tinytemplate = "1.0.3"

[dev-dependencies]
criterion = "0.3.1"

#[[bench]]
#name = "my_benchmark"
#harness = false
#debug = true
